const DOOR_WOOD_TEXTURE = "images/door_finishes/Default_RedOak.png";

const CLICK_LEFT_PANEL = "L";
const CLICK_CENTER_PANEL = "C";
const CLICK_RIGHT_PANEL = "R";

const LOCATION_TOP = "TOP";
const LOCATION_BOTTOM = "BOTTOM";

const MOVE_UP_CODE = 38;
const MOVE_DOWN_CODE = 40;
const MOVE_LEFT_CODE = 37;
const MOVE_RIGHT_CODE = 39;

const IS_OVERLAP = -1;

/** Constants related to panel dimension */
const MIN_ARCH_TRANSOM_HEIGHT = 12;
const MIN_GLASS_WINDOW_WIDTH = 5;
const MIN_GLASS_WINDOW_HEIGHT = 10;
const MIN_LOUVER_WIDTH = 10;
const MIN_LOUVER_HEIGHT = 5;

const DEFAULT_SIDELITE_WIDTH = 38400; // 12 inches
const MIN_SIDELITE_HEIGHT = 38400 / 2; // 6 inches
const DEFAULT_TRANSOM_HEIGHT = 38400; // 12 inches
const DEFAULT_INCREMENT_VALUE = 3200; // 1 inch

const MAX_ELEVATION_WIDTH = 150;
const MAX_ELEVATION_HEIGHT = 100;

const PANEL_WIDTH_UNIT_X_PANEL = 4.608;
const PANEL_WIDTH_UNIT_X_DOOR = 4.47; /* 4.57 */
const PANEL_WIDTH_UNIT_X_TRANSOM = 4.608; /* 4.65 */
const PANEL_WIDTH_UNIT_Y = PANEL_WIDTH_UNIT_X_PANEL * 2; /* 17.6 */
const PANEL_WIDTH_UNIT_Y_TRANSOM = 17.6 / 12;
const PANEL_WIDTH_UNIT_Z = 4.608;
const WIDTH_DIVIDER_FACTOR = 36; /*36.125*/
const HEIGHT_DIVIDER_FACTOR = WIDTH_DIVIDER_FACTOR; /* 84 */
const THICKNESS_DIVIDER_FACTOR = 36;
const FRAME_BLOCK_WIDTH = 7.82;
const FRAME_BLOCK_HEIGHT = 4.77;
const FRAME_BLOCK_UNIT_WIDTH = 1;
const FRAME_BLOCK_UNIT_HEIGHT = 1;
const DOOR_COMP_BLOCK_UNIT_WIDTH = 1 / 10;
const DOOR_COMP_BLOCK_UNIT_HEIGHT = 1 / 10;
const PANEL_PADDING = 0.1;
const STILE_RAIL_THICKNESS = 0.02;
const DOOR_COMPONENT_FRAME_EXTRA_THICKNESS = 0.1;

const DOOR_WIDTH_DEDUCTION = FRAME_BLOCK_WIDTH + 0.4;
const DOOR_HEIGHT_DEDUCTION = FRAME_BLOCK_HEIGHT + 0.3;

const panelWidthUnitXPanel = PANEL_WIDTH_UNIT_X_PANEL;
const panelWidthUnitXDoor = PANEL_WIDTH_UNIT_X_DOOR;
const panelWidthUnitXTransom = PANEL_WIDTH_UNIT_X_TRANSOM;
const panelWidthUnitY = PANEL_WIDTH_UNIT_Y;
const panelWidthUnitYTransom = PANEL_WIDTH_UNIT_Y_TRANSOM;

const WIDTH_ASPECT_FACTOR_GLOBAL =
  PANEL_WIDTH_UNIT_X_PANEL / WIDTH_DIVIDER_FACTOR;
const HEIGHT_ASPECT_FACTOR_GLOBAL = 2 * WIDTH_ASPECT_FACTOR_GLOBAL;

/** Main Panel's Dimension  */
const mainPanelWidth = 0;
const mainPanelHeight = 0;
const panelCountToAdded = 0;

const GLASS_TYPE_DOOR = "Door";

const ELEVATION_FACE_FRONT_NAME = "Face1";
const ELEVATION_FACE_BACK_NAME = "Face2";

// Ctrl key
const CTRL_KEY_CODE = 17;

const DEFAULT_CAMERA_FOV = 40;

const FRAME_BLOCK_CLASH_VALUE = 1.2;

const LOCATION_TE = "TE";
const LOCATION_BE = "BE";
const LOCATION_LE = "LE";
const LOCATION_RE = "RE";

// Line Type - 'Solid'/'Dashed'
const LINE_TYPE_SOLID = "Solid";
const LINE_TYPE_DASH = "Dash";

// Name of Hardwares
const HN_DOOR_HARDWARE = "Door_Hardware";
const HN_GLASS_HARDWARE = "GlassHardware";
const HN_EXCLAMATION = "Exclamation";
const HN_FRAME_NAME = "FRAME";
const HN_FRAME_NAME_ARCH_TRANSOM = "FRAME_ARCH_TRANSOM";
const HN_FRAME_NAME_ARCH_TRANSOM_HOLE = "FRAME_ARCH_TRANSOM_HOLE";
const HN_FRAME_NAME_ARCH_TRANSOM_GLASS = "FRAME_ARCH_TRANSOM_GLASS";
const HN_FRAME_NAME_ARCH_TRANSOM_DIVISON = "FRAME_ARCH_TRANSOM_DIVISION";
const HN_FRAME_NAME_ARCH_TRANSOM_DIVISON_MEASUREMENT =
  "FRAME_ARCH_TRANSOM_DIVISION_MEASUREMENT";
const HN_FRAME_NAME_DOOR_COMPONENT_MEASUREMENT =
  "FRAME_DOOR_COMPONENT_MEASUREMENT";
const HN_FRAME_NAME_DOOR_COMPONENT_MEASUREMENT_LABEL_H =
  "FRAME_DOOR_COMPONENT_MEASUREMENT_LABEL_H";
const HN_FRAME_NAME_DOOR_COMPONENT_MEASUREMENT_LABEL_V =
  "FRAME_DOOR_COMPONENT_MEASUREMENT_LABEL_V";
const HN_FRAME_NAME_LITE_LEFT_EDGE = "FRAME_LITE_FRAME_LEFT_EDGE";
const HN_FRAME_NAME_LITE_RIGHT_EDGE = "FRAME_LITE_FRAME_RIGHT_EDGE";
const HN_FRAME_NAME_LITE_BOTTOM_EDGE = "FRAME_LITE_FRAME_BOTTOM_EDGE";
const HN_FRAME_NAME_LITE_TOP_EDGE = "FRAME_LITE_FRAME_TOP_EDGE";
const HN_FRAME_NAME_LITE_FRAME = "FRAME_LITE_FRAME";
const HN_FRAME_NAME_LITE_GLASS = "FRAME_LITE_GLASS";
const HN_FRAME_NAME_CUTOUT_LEFT_EDGE = "FRAME_CUTOUT_FRAME_LEFT_EDGE";
const HN_FRAME_NAME_CUTOUT_RIGHT_EDGE = "FRAME_CUTOUT_FRAME_RIGHT_EDGE";
const HN_FRAME_NAME_CUTOUT_BOTTOM_EDGE = "FRAME_CUTOUT_FRAME_BOTTOM_EDGE";
const HN_FRAME_NAME_CUTOUT_TOP_EDGE = "FRAME_CUTOUT_FRAME_TOP_EDGE";
const HN_FRAME_NAME_CUTOUT_HOLE = "FRAME_CUTOUT_HOLE";
const HN_FRAME_NAME_LOUVER_LEFT_EDGE = "FRAME_LOUVER_FRAME_LEFT_EDGE";
const HN_FRAME_NAME_LOUVER_RIGHT_EDGE = "FRAME_LOUVER_FRAME_RIGHT_EDGE";
const HN_FRAME_NAME_LOUVER_TOP_EDGE = "FRAME_LOUVER_FRAME_TOP_EDGE";
const HN_FRAME_NAME_LOUVER_BOTTOM_EDGE = "FRAME_LOUVER_FRAME_BOTTOM_EDGE";
const HN_FRAME_NAME_LOUVER_FRAME = "FRAME_LOUVER_FRAME";
const HN_FRAME_NAME_CUTOUT_FRAME = "FRAME_CUTOUT_FRAME";
const HN_FRAME_NAME_LOUVER_GRILL = "FRAME_LOUVER_GRILL";
const HN_CUTOUT = "CUTOUT";
const HN_LOUVER = "LOUVER";
const HN_LITE = "LITE";
const HN_FRAME_NAME_L = "FRAME_LEFT";
const HN_FRAME_NAME_R = "FRAME_RIGHT";
const HN_FRAME_NAME_T = "FRAME_TOP";
const HN_FRAME_NAME_B = "FRAME_BOTTOM";
const HN_FRAME_NAME_PROFILE = "FRAME_PROFILE";
const HN_FRAME_NAME_GLASS = "FRAME_GLASS";
const HN_FRAME_NAME_DOOR = "FRAME_DOOR";
const HN_FRAME_NAME_MID_WIDTH = "FRAME_MID_WIDTH";
const HN_FRAME_NAME_MID_HEIGHT = "FRAME_MID_HEIGHT";
const HN_FRAME_NAME_LEFT_STILE = "FRAME_LEFT_STILE";
const HN_FRAME_NAME_RIGHT_STILE = "FRAME_RIGHT_STILE";
const HN_FRAME_NAME_BOTTOM_RAIL = "FRAME_BOTTOM_RAIL";
const HN_FRAME_NAME_TOP_RAIL = "FRAME_TOP_RAIL";
const HN_LABEL_LINE_V = "LABEL_LINE_V";
const HN_LABEL_LINE_H = "LABEL_LINE_H";
const HN_LABEL_H = "LABEL_H";
const HN_LABEL_V = "LABEL_V";
const HN_DESIGN_MEASUREMENT = "HN_DESIGN_MEASUREMENT";
const HN_OPENING_MEASUREMENT = "HN_OPENING_MEASUREMENT";
const HN_DOOR_MEASUREMENT = "HN_DOOR_MEASUREMENT";
const HN_SEGMENT_MEASUREMENT = "HN_SEGMENT_MEASUREMENT";
const HN_DOOR_SEGMENT_MEASUREMENT = "HN_DOOR_SEGMENT_MEASUREMENT";
const HN_PANEL_MEASUREMENT = "HN_PANEL_MEASUREMENT";
const HN_FRAME_MEMBER = "FRAME_MEMBER";
const HN_FRAME_MEMBER_HORIZONTAL = "FRAME_MEMBER_HORIZONTAL";
const HN_FRAME_MEMBER_VERTICAL = "FRAME_MEMBER_VERTICAL";
const HN_FRAME_MEMBER_MARKER = "FRAME_MEMBER_MARKER";
const HN_FRAME_MEMBER_MARKER_CIRCLE = "FRAME_MEMBER_MARKER_CIRCLE";
const HN_FRAME_PROFILE_COMPONENT = "FRAME_PROFILE_COMPONENT";
const HN_FRAME_TEXT_ANNOTATION = "FRAME_TEXT_ANNOTATION";
const HN_FRAME_MEMBER_JOINT_MARKER = "FRAME_MEMBER_JOINT_MARKER";
const HN_JOINT_LINE = "HN_JOINT_LINE";
const HN_SWING_DIRECTION = "HN_SWING_DIRECTION";
const HN_FRAME_PANEL = "FRAME_PANEL";
const HN_DOOR_SWING_DIRECTION = "HN_DOOR_SWING_DIRECTION";

const ANNOTATION = "ANNOTATION";

const HN_LINE = "Line";
const HN_GLASS_HARDWARE_HOLE = "GlassHardwareHole";
const HN_GLASS_HARDWARE_HOLE_CIRCLE = "GlassHardwareHoleCircle";

const HDW_TYPE_LOUVER = "HDW_TYPE_LOUVER";
const HDW_TYPE_DOOR_LITE = "HDW_TYPE_DOOR_LITE";
const HDW_TYPE_CUTOUT = "HDW_TYPE_CUTOUT";

const ALIGN_CENTER = "center";
const ALIGN_UP = "up";
const ALIGN_DOWN = "down";
const ALIGN_LEFT = "left";
const ALIGN_RIGHT = "right";
const ALIGNMENT_H = "alignment_horizontal";
const ALIGNMENT_V = "alignment_vertical";

// Annotaion Parameters
const HDW_POSITION_START = "START";
const HDW_POSITION_END = "END";
const DIMENSION_MEASUREMENT_MANDATORY = "MANDATORY";

const TYPE_CAP = "TYPE_CAP";
const TYPE_LABEL = "TYPE_LABEL";

// Door Type
const DOOR_MATERIAL_WOOD = "Wood";
const DOOR_MATERIAL_HOLLOW_METAL = "Hollow Metal";

// Panel type
const PANEL_MATERIAL_GLASS = "glass";
const PANEL_MATERIAL_OTHER = "other";

// Color code
const COLOR_WHITE = 0xffffff;
const COLOR_GRAY = 0x858585;
const COLOR_ALICE_BLUE = 0xf0f8ff;
const COLOR_TEXT_WHITE = "white";
const COLOR_TEXT_GREEN = "green";
const COLOR_TEXT_BLACK = "black";
const COLOR_TEXT_AA_BLUE = "#157FCC";
const COLOR_TEXT_BLUE = "blue";
const COLOR_TEXT_BROWN = "brown";
const COLOR_PANEL_SPACER = "#adc2d1";

// Wall color
const wallColorCode = 0x34d0d2;

// Camera View
const CAMERA_VIEW_ORTHO = "Orthographic";
const CAMERA_VIEW_PERSPECTIVE = "Perspective";

// Properties
const FONT_PROPERTY_FONT_FACE = "fontface";
const FONT_PROPERTY_FONT_SIZE = "fontsize";
const BORDER_PROPERTY_THICKNESS = "borderThickness";
const BORDER_PROPERTY_COLOR = "borderColor";
const BORDER_PROPERTY_BG_COLOR = "backgroundColor";

const FONT_TYPE_ARIAL = "Arial";
const FONT_STYLE_BOLD = "Bold";
const FONT_PLAIN_10_ARIAL = "10px Arial";
const FONT_BOLD_60_ARIAL = "bold 60px Arial";
const FONT_PLAIN_70_ARIAL = "70px Arial";
const FONT_BOLD_80_ARIAL = "bold 80px Arial";
const FONT_BOLD_90_ARIAL = "bold 90px Arial";
const FONT_PLAIN_90_ARIAL = "90px Arial";
const FONT_PLAIN_100_ARIAL = "100px Arial";
const FONT_BOLD_100_ARIAL = "bold 100px Arial";
const FONT_BOLD_110_ARIAL = "bold 110px Arial";
const FONT_BOLD_145_ARIAL = "bold 145px Arial";

const DIRECTION_LEFT = "Left";
const DIRECTION_RIGHT = "Right";

// Units
const METRIC_UNIT = "METRIC";
const IMPERIAL_UNIT = "IMPERIAL";

// Unit Text representation
const METRIC_UNIT_TEXT = "Millimeters";
const IMPERIAL_UNIT_TEXT = "Inches";

// Special Characters
const UNDERSCORE = "_";
const INCH_REPRESENTATION = "";

const INVALID_VALUE = -1;

// Transom Types
const TRANSOM_TYPE_NONE = "None";
const TRANSOM_TYPE_RECTANGLE = "TRANSOM_TYPE_RECTANGLE";
const TRANSOM_TYPE_ELLIPSE = "TRANSOM_TYPE_ELLIPSE";
const TRANSOM_TYPE_ARCH_HEAD = "TRANSOM_TYPE_ARCH_HEAD";

const SCALE_X = "x";
const SCALE_Y = "y";
const SCALE_Z = "z";
const SCALING_MAIN_FRAMES = "SCALING_MAIN_FRAMES";
const SCALING_LITE_LOUVER = "SCALING_LITE_LOUVER";

const MOUSE_SCROLL_ALL = "all-scroll";
const MOUSE_EW_RESIZE = "ew-resize";
const MOUSE_N_RESIZE = "n-resize";
const MOUSE_DEFAULT = "default";

const MIME_CONTENT_OCTET_STREAM = "image/octet-stream";
const MIME_CONTENT_PNG = "image/png";
const MIME_CONTENT_JPEG = "image/jpeg";
const IMAGE_DATA_TYPE_PNG = "data:image/png;base64,";

const REPORT_SIDE_FRONT = "front";
const REPORT_SIDE_BACK = "back";

const UPDATE_MEASUREMENTS_HORIZONTAL = "UPDATE_MEASUREMENTS_HORIZONTAL";
const UPDATE_MEASUREMENTS_VERTICAL = "UPDATE_MEASUREMENTS_VERTICAL";

// FRAME Names
const FN_OPEN_BACK_CASED = "Open Back Cased";
const FN_OPEN_BACK_DOUBLE_EGRESS = "Open Back Double Egress";
const FN_OPEN_BACK_SINGLE = "Open Back Single";
const FN_OPEN_BACK_EQUAL_UNEQUAL = "Open Back Equal/Unequal";

// Panel Types
const PANEL_TYPE_TRANSOM = "Transom";
const PANEL_TYPE_SPANNING_TRANSOM = "SpanningTransom";
const PANEL_TYPE_DOOR = "Door";
const PANEL_TYPE_SIDELITE = "Sidelite";

const PROPERTY_FROM_LEFT = "fromLeft";
const PROPERTY_FROM_TOP = "fromTop";
const PROPERTY_FROM_BOTTOM = "fromBottom";

const ELEVATION_SHOW_ANNOTATION = "elevationannotation";
const ELEVATION_SHOW_MEASUREMENT = "elevationmeasurement";
const ELEVATION_SHOW_IDENTIFIER = "elevationidentifier";

// Constants for Report FC
const REPORTS_FC_IMAGE_CODE_ARR = [
  "ELEV_FRAME_ONLY",
  "ELEV_FRAME_NOTE",
  "ELEV_FRAME_DIMS",
  "ELEV_FRAME_NOTE_DIMS",
  "ELEV_FRAME_ONLY_LINES",
  "ELEV_FRAME_NOTE_LINES",
  "ELEV_FRAME_DIMS_LINES",
  "ELEV_FRAME_NOTE_DIMS_LINES",
  "ELEV_FRAME_ONLY_THUMB",
  "ELEV_OPENING_FRAME_DOORS",
  "ELEV_OPENING_FRAME_DOORS_NOTE",
  "ELEV_OPENING_FRAME_DOORS_LINES",
  "ELEV_OPENING_FRAME_DOORS_NOTE_DIMS_LINES",
  "ELEV_OPENING_FRAME_DOORS_NOTE_DIMS_LINES_SWING",
  "ELEV_OPENING_FRAME_DOORS_NOTE_LINES_SWING",
];
const REPORTS_DOORS_IMAGE_CODE_ARR = ["ELEV_DOORS", "ELEV_DOOR_DIMS"];
const REPORT_FC_PROFILE_IMAGE_CODE = "ELEV_PROFILE";
const REPORTS_FC_DIMENSION_CODE = "DIMS";
const REPORTS_FC_NOTES_CODE = "NOTE";
const REPORTS_FC_LINES_CODE = "LINES";
const REPORTS_DOORS_CODE = "DOOR";
const REPORTS_FRAMES_CODE = "FRAME";
const REPORTS_OPENING_CODE = "OPENING";
const REPORTS_DOOR_SWING_CODE = "SWING";

// Variable type
const VAR_TYPE_BOOLEAN = "boolean";

// Title
const ANNOTATION_JAMB_TITLE = "Opposite Side Jamb Face = ";
const ANNOTATION_HEAD_TITLE = "Opposite Side Head Face = ";

// Window Visibility states
const WINDOW_VISIBILITY_HIDDEN = "hidden";
const WINDOW_VISIBILITY_VISIBLE = "visible";

/* eslint-enable no-unused-vars */

module.exports = {
  DEFAULT_CAMERA_FOV,
  PANEL_WIDTH_UNIT_X_PANEL,
  PANEL_WIDTH_UNIT_Y,
  panelWidthUnitY,
  SCALING_LITE_LOUVER,
  SCALING_MAIN_FRAMES,
  MOUSE_SCROLL_ALL,
  MOUSE_EW_RESIZE,
  INVALID_VALUE,
  WIDTH_DIVIDER_FACTOR,
  HEIGHT_DIVIDER_FACTOR,
  FRAME_BLOCK_UNIT_WIDTH,
  FRAME_BLOCK_UNIT_HEIGHT,
  HN_FRAME_NAME_L,
  SCALE_X,
  SCALE_Y,
  SCALE_Z,
  MOUSE_N_RESIZE,
  HN_FRAME_NAME_B,
  HN_FRAME_NAME_R,
  HN_FRAME_NAME_T,
  HDW_POSITION_START,
  HDW_POSITION_END,
  FRAME_BLOCK_WIDTH,
  FRAME_BLOCK_HEIGHT,
  THICKNESS_DIVIDER_FACTOR,
  PANEL_WIDTH_UNIT_Z,
  CTRL_KEY_CODE,
  wallColorCode,
  DOOR_WIDTH_DEDUCTION,
  DOOR_HEIGHT_DEDUCTION,
  HN_FRAME_NAME_DOOR,
  GLASS_TYPE_DOOR,
  HN_EXCLAMATION,
  TRANSOM_TYPE_NONE,
  TRANSOM_TYPE_RECTANGLE,
  REPORTS_DOORS_CODE,
  TRANSOM_TYPE_ELLIPSE,
  TRANSOM_TYPE_ARCH_HEAD,
  HN_FRAME_NAME,
  HN_FRAME_NAME_ARCH_TRANSOM,
  HN_FRAME_NAME_ARCH_TRANSOM_HOLE,
  HN_FRAME_NAME_ARCH_TRANSOM_GLASS,
  CLICK_CENTER_PANEL,
  HN_FRAME_NAME_ARCH_TRANSOM_DIVISON,
  HN_FRAME_NAME_ARCH_TRANSOM_DIVISON_MEASUREMENT,
  HN_FRAME_NAME_DOOR_COMPONENT_MEASUREMENT,
  HN_FRAME_NAME_LITE_LEFT_EDGE,
  FONT_BOLD_90_ARIAL,
  HN_FRAME_NAME_LITE_RIGHT_EDGE,
  HN_FRAME_NAME_LITE_BOTTOM_EDGE,
  HN_FRAME_NAME_LITE_TOP_EDGE,
  HN_FRAME_NAME_LITE_FRAME,
  HN_FRAME_NAME_LITE_GLASS,
  HN_FRAME_NAME_LOUVER_LEFT_EDGE,
  HN_FRAME_NAME_LOUVER_RIGHT_EDGE,
  HN_FRAME_NAME_LOUVER_TOP_EDGE,
  HN_FRAME_NAME_LOUVER_BOTTOM_EDGE,
  HN_FRAME_NAME_LOUVER_FRAME,
  HN_FRAME_NAME_LOUVER_GRILL,
  HDW_TYPE_LOUVER,
  HDW_TYPE_DOOR_LITE,
  FONT_PLAIN_70_ARIAL,
  TYPE_CAP,
  TYPE_LABEL,
  FONT_BOLD_80_ARIAL,
  HN_GLASS_HARDWARE,
  HN_LABEL_V,
  HN_LABEL_H,
  HN_LABEL_LINE_H,
  HN_LABEL_LINE_V,
  IS_OVERLAP,
  LOCATION_BE,
  LOCATION_TE,
  LOCATION_RE,
  LOCATION_LE,
  COLOR_ALICE_BLUE,
  COLOR_GRAY,
  COLOR_WHITE,
  FONT_PROPERTY_FONT_FACE,
  FONT_TYPE_ARIAL,
  FONT_PROPERTY_FONT_SIZE,
  ALIGN_DOWN,
  BORDER_PROPERTY_THICKNESS,
  BORDER_PROPERTY_COLOR,
  BORDER_PROPERTY_BG_COLOR,
  FONT_STYLE_BOLD,
  panelWidthUnitXPanel,
  panelWidthUnitXDoor,
  panelWidthUnitXTransom,
  panelWidthUnitYTransom,
  CAMERA_VIEW_ORTHO,
  CAMERA_VIEW_PERSPECTIVE,
  ELEVATION_FACE_FRONT_NAME,
  ELEVATION_FACE_BACK_NAME,
  HN_FRAME_MEMBER_MARKER,
  MAX_ELEVATION_HEIGHT,
  FONT_BOLD_60_ARIAL,
  DIRECTION_RIGHT,
  HN_FRAME_NAME_MID_WIDTH,
  HN_FRAME_NAME_MID_HEIGHT,
  DOOR_COMP_BLOCK_UNIT_WIDTH,
  DOOR_COMP_BLOCK_UNIT_HEIGHT,
  HN_DOOR_SEGMENT_MEASUREMENT,
  HN_FRAME_NAME_GLASS,
  FRAME_BLOCK_CLASH_VALUE,
  MIN_ARCH_TRANSOM_HEIGHT,
  MIN_GLASS_WINDOW_WIDTH,
  MIN_GLASS_WINDOW_HEIGHT,
  MIN_LOUVER_WIDTH,
  MIN_LOUVER_HEIGHT,
  HN_DOOR_HARDWARE,
  INCH_REPRESENTATION,
  mainPanelWidth,
  mainPanelHeight,
  panelCountToAdded,
  MIME_CONTENT_OCTET_STREAM,
  MIME_CONTENT_PNG,
  MIME_CONTENT_JPEG,
  IMAGE_DATA_TYPE_PNG,
  HN_GLASS_HARDWARE_HOLE,
  HN_GLASS_HARDWARE_HOLE_CIRCLE,
  HN_LINE,
  DOOR_MATERIAL_HOLLOW_METAL,
  DOOR_MATERIAL_WOOD,
  MOUSE_DEFAULT,
  HN_FRAME_NAME_DOOR_COMPONENT_MEASUREMENT_LABEL_H,
  HN_FRAME_NAME_DOOR_COMPONENT_MEASUREMENT_LABEL_V,
  REPORT_SIDE_FRONT,
  REPORT_SIDE_BACK,
  HN_FRAME_NAME_LEFT_STILE,
  HN_FRAME_NAME_RIGHT_STILE,
  HN_FRAME_NAME_BOTTOM_RAIL,
  ALIGN_UP,
  HN_FRAME_NAME_TOP_RAIL,
  ALIGN_CENTER,
  ALIGN_LEFT,
  ALIGN_RIGHT,
  ALIGNMENT_H,
  ALIGNMENT_V,
  UPDATE_MEASUREMENTS_HORIZONTAL,
  UPDATE_MEASUREMENTS_VERTICAL,
  COLOR_TEXT_WHITE,
  COLOR_TEXT_GREEN,
  COLOR_TEXT_BLUE,
  COLOR_TEXT_BROWN,
  METRIC_UNIT,
  IMPERIAL_UNIT,
  METRIC_UNIT_TEXT,
  IMPERIAL_UNIT_TEXT,
  DIMENSION_MEASUREMENT_MANDATORY,
  REPORTS_OPENING_CODE,
  FN_OPEN_BACK_CASED,
  FN_OPEN_BACK_DOUBLE_EGRESS,
  FN_OPEN_BACK_SINGLE,
  COLOR_PANEL_SPACER,
  FN_OPEN_BACK_EQUAL_UNEQUAL,
  FONT_PLAIN_10_ARIAL,
  PANEL_TYPE_TRANSOM,
  CLICK_RIGHT_PANEL,
  CLICK_LEFT_PANEL,
  PANEL_TYPE_SPANNING_TRANSOM,
  PANEL_TYPE_DOOR,
  PANEL_TYPE_SIDELITE,
  DIRECTION_LEFT,
  HN_FRAME_NAME_PROFILE,
  HN_OPENING_MEASUREMENT,
  ANNOTATION,
  HN_DOOR_MEASUREMENT,
  HN_FRAME_MEMBER_HORIZONTAL,
  HN_FRAME_MEMBER_VERTICAL,
  HN_FRAME_MEMBER,
  PROPERTY_FROM_LEFT,
  PROPERTY_FROM_TOP,
  PROPERTY_FROM_BOTTOM,
  LOCATION_TOP,
  LOCATION_BOTTOM,
  FONT_PLAIN_100_ARIAL,
  COLOR_TEXT_AA_BLUE,
  DEFAULT_SIDELITE_WIDTH,
  DEFAULT_TRANSOM_HEIGHT,
  HN_FRAME_PROFILE_COMPONENT,
  HN_PANEL_MEASUREMENT,
  ELEVATION_SHOW_ANNOTATION,
  ELEVATION_SHOW_MEASUREMENT,
  ELEVATION_SHOW_IDENTIFIER,
  HN_FRAME_MEMBER_MARKER_CIRCLE,
  COLOR_TEXT_BLACK,
  HN_FRAME_TEXT_ANNOTATION,
  HN_FRAME_MEMBER_JOINT_MARKER,
  WIDTH_ASPECT_FACTOR_GLOBAL,
  HEIGHT_ASPECT_FACTOR_GLOBAL,
  PANEL_MATERIAL_GLASS,
  REPORTS_FC_IMAGE_CODE_ARR,
  REPORTS_FC_DIMENSION_CODE,
  REPORTS_FC_NOTES_CODE,
  REPORTS_FC_LINES_CODE,
  HN_JOINT_LINE,
  HN_SWING_DIRECTION,
  PANEL_PADDING,
  FONT_PLAIN_90_ARIAL,
  HN_FRAME_PANEL,
  FONT_BOLD_100_ARIAL,
  MOVE_UP_CODE,
  MOVE_DOWN_CODE,
  MOVE_LEFT_CODE,
  MOVE_RIGHT_CODE,
  DEFAULT_INCREMENT_VALUE,
  HN_DESIGN_MEASUREMENT,
  REPORT_FC_PROFILE_IMAGE_CODE,
  FONT_BOLD_110_ARIAL,
  FONT_BOLD_145_ARIAL,
  VAR_TYPE_BOOLEAN,
  ANNOTATION_JAMB_TITLE,
  ANNOTATION_HEAD_TITLE,
  PANEL_MATERIAL_OTHER,
  DOOR_WOOD_TEXTURE,
  WINDOW_VISIBILITY_HIDDEN,
  WINDOW_VISIBILITY_VISIBLE,
  STILE_RAIL_THICKNESS,
  HN_LOUVER,
  HN_LITE,
  DOOR_COMPONENT_FRAME_EXTRA_THICKNESS,
  HN_FRAME_NAME_CUTOUT_HOLE,
  HDW_TYPE_CUTOUT,
  HN_FRAME_NAME_CUTOUT_FRAME,
  HN_CUTOUT,
  HN_FRAME_NAME_CUTOUT_LEFT_EDGE,
  HN_FRAME_NAME_CUTOUT_RIGHT_EDGE,
  REPORTS_FRAMES_CODE,
  HN_FRAME_NAME_CUTOUT_BOTTOM_EDGE,
  HN_FRAME_NAME_CUTOUT_TOP_EDGE,
  HN_DOOR_SWING_DIRECTION,
  HN_SEGMENT_MEASUREMENT,
  REPORTS_DOOR_SWING_CODE,
  REPORTS_DOORS_IMAGE_CODE_ARR,
  MAX_ELEVATION_WIDTH,
  MIN_SIDELITE_HEIGHT,
};
